language: node_js
node_js:
  - 0.8
before_script:
  - mysql -e 'CREATE DATABASE popcorn;'
  - node make check
notifications:
  irc:
    channels:
      - "irc.mozilla.org#popcorn"
    on_success: change
